language: cpp
dist: bionic
compiler:
  - gcc
before_install:
  - sudo apt-get install -y qt5-default qt5-qmake clang-format
install:
  - ls
script:
  - qmake
  - make -j 2
after_success:
  - clang-format -i -style=LLVM *.cpp *.h
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add *.cpp *.h
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git commit --message "Travis AUTO FORMAT"
  - git remote add master https://${GH_TOKEN}@github.com/Lightjohn/QtFileExplorer.git > /dev/null 2>&1
  - git push --set-upstream master HEAD
env:
  global:
    secure: USg7sjWCb69vKpA28diczd2Kj2saZBzqulaCoA0vL4XBjrH8Aacb1r+8z/SJbtsDZXXbQkCkL25NeYq8GLHbOBAm0XbohTSZNnYolV0/TFHTaQ4rVlOu/pN0emgRZmhaGX8kW/ezUx4i10u52jtgxmZh9Aoe5KwJgszYTPsRAZ0=
