language: cpp
dist: bionic
compiler:
  - gcc
before_install:
  - sudo apt-get install -y qt5-default qt5-qmake clang-format
install:
  - ls
script:
  - qmake
  - make -j 2
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout master
  - clang-format -i -style=LLVM *.cpp *.h
  - git add *.cpp *.h
  - git commit --message "[ci skip] Travis AUTO FORMAT"
  - git push https://${GH_TOKEN}@github.com/Lightjohn/QtFileExplorer.git --quiet > /dev/null 2>&1
